/* GENERATED by scripts/process-assets.mjs — do not edit by hand. */

export const assetSizes = {
  'app-full-plan': { w: 2340, h: 1932 },
  'app-full-dialog': { w: 2340, h: 1932 },
  'app-full-result': { w: 2340, h: 1932 },
  'pane-listening': { w: 1678, h: 1872 },
  'pane-checks-2': { w: 1678, h: 1872 },
  'pane-checks-4': { w: 1678, h: 1872 },
  'pane-thinking': { w: 1678, h: 1872 },
  'pane-thinking-5s': { w: 1678, h: 1872 },
  'pane-plan': { w: 1678, h: 1872 },
  'pane-plan-hover': { w: 1678, h: 1872 },
  'pane-plan-typed': { w: 1678, h: 1872 },
  'pane-sent': { w: 1678, h: 1872 },
  'pane-result': { w: 1678, h: 1872 },
  'crop-situation': { w: 2286, h: 504 },
  'crop-checked': { w: 2232, h: 486 },
  'crop-plan-list': { w: 2232, h: 882 },
  'crop-cta': { w: 2184, h: 210 },
  'crop-talk-note': { w: 2136, h: 120 },
  'crop-cta-hover': { w: 2184, h: 210 },
  'crop-typed': { w: 2268, h: 216 },
  'crop-dialog': { w: 1542, h: 810 },
  'crop-sent': { w: 2184, h: 186 },
  'crop-executing': { w: 2268, h: 324 },
  'crop-done': { w: 2232, h: 504 },
  'crop-verify': { w: 2232, h: 264 },
  'card-listening': { w: 2316, h: 1110 },
  'card-checks-2': { w: 2316, h: 1110 },
  'card-checks-4': { w: 2316, h: 1110 },
  'card-thinking': { w: 2316, h: 1110 },
  'card-thinking-5s': { w: 2316, h: 1110 },
  'crop-bubble': { w: 912, h: 280 },
  'crop-looking': { w: 2304, h: 228 },
  'tile-startup': { w: 712, h: 480 },
  'tile-disk': { w: 712, h: 480 },
  'tile-installers': { w: 712, h: 480 },
  'tile-background': { w: 744, h: 480 },
  'plan-item-1': { w: 1920, h: 248 },
  'plan-item-2': { w: 1920, h: 248 },
  'plan-item-3': { w: 1920, h: 248 },
  'plan-item-4': { w: 1920, h: 248 },
  'res-startup': { w: 744, h: 264 },
  'res-temp': { w: 760, h: 264 },
  'res-boot': { w: 800, h: 264 },
  'crop-done-word': { w: 1200, h: 208 },
} as const;

export type AssetName = keyof typeof assetSizes;

/** Height that keeps `name` at its true aspect ratio when drawn `width` wide. */
export const heightFor = (name: AssetName, width: number) =>
  (width * assetSizes[name].h) / assetSizes[name].w;
