#!/usr/bin/env python3
"""Emit src/script.ts from the validated script_manifest.json.

The manifest is the single source of truth: it is what passed
validate_motion_script.py, so the video must never drift from it.
"""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent
d = json.loads((root.parent / 'script_manifest.json').read_text())

# The through-line's height, block by block: the stack grows monotonically
# through the build, peaks on the approval, then unwinds to a single card.
CARDS = {1: 1, 2: 6, 3: 12, 4: 20, 5: 26, 6: 31,
         7: 36, 8: 40, 9: 44, 10: 41, 11: 3, 12: 1}

lines = ["// GENERATED by gen-script.py from ../script_manifest.json — do not edit by hand.",
         "export type Block = {",
         "  n: number;",
         "  role: string;",
         "  line: string;",
         "  cards: number;",
         "};",
         "",
         "export const BLOCKS: Block[] = ["]
for b in d['blocks']:
    line = b['vo_line'].replace('\\', '\\\\').replace("'", "\\'")
    lines.append(
        f"  {{ n: {b['n']}, role: '{b['arc_role']}', cards: {CARDS[b['n']]}, line: '{line}' }},")
lines += ["];", "",
          f"export const TAGLINE = \"Noah finds what's actually wrong with your Mac.\";"]
(root / 'src' / 'script.ts').write_text('\n'.join(lines) + '\n')
print(f'wrote src/script.ts — {len(d["blocks"])} blocks')
