// Inlines Plus Jakarta Sans as data URIs. loadFont() + delayRender() raced and
// timed out across the render's parallel workers; embedding the faces removes
// the fetch (and the delay) altogether.
import {readFileSync, writeFileSync} from 'node:fs';

const weights = [400, 500, 600, 700];
const faces = weights
  .map((w) => {
    const b64 = readFileSync(`public/fonts/pjs-${w}.woff2`).toString('base64');
    return `@font-face{font-family:'PlusJakartaSans';font-style:normal;font-weight:${w};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}`;
  })
  .join('\n');

writeFileSync(
  'src/fontFaces.ts',
  `// GENERATED by scripts/gen-fonts.mjs — do not hand-edit.\nexport const PJS_FACES = \`\n${faces}\n\`;\n`
);
console.log('src/fontFaces.ts written,', (faces.length / 1024).toFixed(0) + 'KB');
