// GENERATED by gen-script.py from ../script_manifest.json — do not edit by hand.
export type Block = {
  n: number;
  role: string;
  line: string;
  cards: number;
};

export const BLOCKS: Block[] = [
  { n: 1, role: 'hook', cards: 1, line: 'Your Mac is slow. It is probably not junk, and the cleaner you just ran already emptied every cache you have.' },
  { n: 2, role: 'build', cards: 6, line: 'The counter climbs past eighteen hundred problems found. None of them is the reason your fan has run all afternoon.' },
  { n: 3, role: 'build', cards: 12, line: 'Noah is a desktop app for macOS. It is not a chat window that hands you a Terminal command and wishes you luck.' },
  { n: 4, role: 'build', cards: 20, line: 'A browser tab cannot see your machine. Noah runs outside that sandbox, so it can read what your Mac is actually doing.' },
  { n: 5, role: 'build', cards: 26, line: 'You describe the symptom in your own words. My fan will not stop is a complete and valid bug report here.' },
  { n: 6, role: 'build', cards: 31, line: 'Noah runs audited diagnostics against troubleshooting playbooks that ship inside the app. They name the cause rather than counting things that look untidy.' },
  { n: 7, role: 'build', cards: 36, line: 'The answer is usually dull and specific. A login item from an app you deleted, or stale preferences left behind by an update.' },
  { n: 8, role: 'build', cards: 40, line: 'Then Noah answers in plain English. One short sentence names the actual cause, and the next names exactly what it proposes to change.' },
  { n: 9, role: 'build', cards: 44, line: 'Nothing runs until you approve. Every action appears on screen before it happens, and the button is yours to press or refuse.' },
  { n: 10, role: 'build', cards: 41, line: 'Every action is logged, and all of it is reversible. Noah moves the old file aside rather than deleting anything blind.' },
  { n: 11, role: 'turn', cards: 3, line: 'Do not trust any of that. The desktop client is open source, so anyone can read what Noah is allowed to touch.' },
  { n: 12, role: 'payoff', cards: 1, line: 'One thousand eight hundred issues was never the count. It was always one, and the fan you heard all afternoon has stopped.' },
];

export const TAGLINE = "Noah finds what's actually wrong with your Mac.";
